(()=>{const journeys=Array.isArray(window.MIAOSHU_JOURNEYS)?[...window.MIAOSHU_JOURNEYS].sort((a,b)=>b.date.localeCompare(a.date)):[];const timeline=document.getElementById("journey-timeline"),map=document.getElementById("journey-map"),filters=document.getElementById("journey-filters"),detail=document.getElementById("journey-detail"),nodes=document.getElementById("journey-nodes");if(!timeline||!map||!filters||!detail||!nodes||!journeys.length)return;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const bounds={minLat:21.8,maxLat:25.5,minLng:119.3,maxLng:122.1};let activeRegion="全部",activeYear="全部",selected=null;
const pos=l=>({x:Math.max(8,Math.min(92,8+((l.lng-bounds.minLng)/(bounds.maxLng-bounds.minLng))*84)),y:Math.max(8,Math.min(92,8+((bounds.maxLat-l.lat)/(bounds.maxLat-bounds.minLat))*84))});
const visible=()=>journeys.filter(j=>(activeRegion==="全部"||j.region===activeRegion)&&(activeYear==="全部"||j.date.startsWith(activeYear+"-")));
function select(id,source){const j=journeys.find(x=>x.id===id);if(!j)return;selected=id;document.querySelectorAll("[data-journey-id]").forEach(el=>el.classList.toggle("is-active",el.dataset.journeyId===id));detail.innerHTML='<span>'+esc(j.date)+' · '+esc(j.region)+'</span><strong>'+esc(j.title)+'</strong><small>'+esc(j.location.name)+' · '+esc(j.journeyPoints.join(" → "))+'</small><div class="journey-detail-actions"><a href="'+esc(j.articleUrl)+'">閱讀札記 →</a>'+(j.documentUrl?'<a href="'+esc(j.documentUrl)+'" target="_blank" rel="noopener">閱讀 PDF ↗</a>':"")+'<button type="button" data-show-timeline="'+esc(j.id)+'">在時間軸查看 ↓</button></div>';history.replaceState(null,"","?journey="+encodeURIComponent(id)+"#journey-map-title");if(source==="timeline")document.querySelector('.journey-node[data-journey-id="'+CSS.escape(id)+'"]')?.focus({preventScroll:true})}
function render(){const list=visible();timeline.innerHTML=list.map(j=>{const p=j.date.split("-");return '<li tabindex="0" data-journey-id="'+esc(j.id)+'" id="timeline-'+esc(j.id)+'"><time datetime="'+esc(j.date)+'"><span>'+p[0]+'</span>'+p[1]+'.'+p[2]+'</time><div><span class="timeline-type">'+esc(j.region+"・"+j.category)+'</span><h3>'+esc(j.title)+'</h3><p>'+esc(j.summary)+'</p><a href="'+esc(j.articleUrl)+'">閱讀這篇札記 ↓</a></div></li>'}).join("");
const groups=new Map();list.forEach(j=>{const key=j.region;const g=groups.get(key)||[];g.push(j);groups.set(key,g)});nodes.innerHTML=[...groups.entries()].map(([region,items])=>{const lat=items.reduce((a,j)=>a+j.location.lat,0)/items.length,lng=items.reduce((a,j)=>a+j.location.lng,0)/items.length,p=pos({lat,lng});if(items.length===1){const j=items[0];return '<button type="button" class="journey-node" data-journey-id="'+esc(j.id)+'" style="left:'+p.x+'%;top:'+p.y+'%" aria-label="'+esc(j.region+"・"+j.location.name+"："+j.title)+'"><span>1</span></button>'}return '<button type="button" class="journey-node journey-cluster" data-region-cluster="'+esc(region)+'" style="left:'+p.x+'%;top:'+p.y+'%" aria-label="'+esc(region+"，"+items.length+"篇札記")+'"><span>'+items.length+'</span></button>'}).join("");
timeline.querySelectorAll("[data-journey-id]").forEach(el=>{el.addEventListener("click",e=>{if(!e.target.closest("a"))select(el.dataset.journeyId,"timeline")});el.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();select(el.dataset.journeyId,"timeline")}})});nodes.querySelectorAll("[data-journey-id]").forEach(b=>b.addEventListener("click",()=>select(b.dataset.journeyId,"map")));nodes.querySelectorAll("[data-region-cluster]").forEach(b=>b.addEventListener("click",()=>{activeRegion=b.dataset.regionCluster;syncFilters();render()}));if(list.length)select(list.some(x=>x.id===selected)?selected:list[0].id)}
function syncFilters(){filters.querySelectorAll("button").forEach(b=>{const region=b.dataset.region,year=b.dataset.year;b.classList.toggle("is-active",(region&&region===activeRegion)||(year&&year===activeYear))})}
const regions=["全部",...new Set(journeys.map(j=>j.region))],years=["全部",...new Set(journeys.map(j=>j.date.slice(0,4)))];filters.innerHTML='<span class="journey-filter-label">年份</span>'+years.map((y,i)=>'<button type="button" data-year="'+esc(y)+'" class="'+(i?"":"is-active")+'">'+esc(y)+'</button>').join("")+'<span class="journey-filter-label">地區</span>'+regions.map((r,i)=>'<button type="button" data-region="'+esc(r)+'" class="'+(i?"":"is-active")+'">'+esc(r)+'</button>').join("");filters.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.region)activeRegion=b.dataset.region;if(b.dataset.year)activeYear=b.dataset.year;syncFilters();render()});detail.addEventListener("click",e=>{const b=e.target.closest("[data-show-timeline]");if(!b)return;document.getElementById("timeline-"+b.dataset.showTimeline)?.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"center"})});
const deep=new URLSearchParams(location.search).get("journey");if(deep&&journeys.some(j=>j.id===deep)){activeRegion=journeys.find(j=>j.id===deep).region;selected=deep;syncFilters()}render();
})();